/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/movements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List one page of the active cycle's movements */
        get: operations["listMovements"];
        put?: never;
        /** Record a movement */
        post: operations["createMovement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/movements/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace a movement's amount, direction, category, date, and note */
        put: operations["updateMovement"];
        post?: never;
        /** Delete a movement */
        delete: operations["deleteMovement"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all categories */
        get: operations["listCategories"];
        put?: never;
        /** Create a category */
        post: operations["createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cycles/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active cycle bounds and balance */
        get: operations["getCurrentCycle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/widgets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the stored dashboard widget selection */
        get: operations["getWidgetSettings"];
        /** Replace the whole dashboard widget selection */
        put: operations["putWidgetSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/habit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Logging streak, XP and level for the active cycle
         * @description Derived on every request from the movements that exist now. A day counts as logged when a movement was created on it (in the configured time zone), whatever date the movement carries.
         */
        get: operations["getHabit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Movement: {
            /** Format: int64 */
            id: number;
            /**
             * Format: int64
             * @description Positive amount, in cents
             */
            amount_cents: number;
            /** @enum {string} */
            direction: "in" | "out";
            /** Format: int64 */
            category_id: number;
            /** Format: date */
            occurred_on: string;
            note: string;
            /** Format: date-time */
            created_at: string;
        };
        MovementPage: {
            /** @description Up to 6 movements, by date then most recently recorded */
            items: components["schemas"]["Movement"][];
            /** @description The page returned, from 1 */
            page: number;
            /** @description At least 1, also for an empty cycle */
            total_pages: number;
            /** @description Movements in the active cycle */
            total: number;
        };
        MovementInput: {
            /**
             * Format: int64
             * @description Positive amount, in cents
             */
            amount_cents: number;
            /** @enum {string} */
            direction: "in" | "out";
            /** Format: int64 */
            category_id: number;
            /** Format: date */
            occurred_on: string;
            /** @default  */
            note: string;
        };
        Category: {
            /** Format: int64 */
            id: number;
            name: string;
            /**
             * @description Only movements with this direction may use the category
             * @enum {string}
             */
            direction: "in" | "out";
            sort_order: number;
        };
        CategoryInput: {
            name: string;
            /** @enum {string} */
            direction: "in" | "out";
        };
        CurrentCycle: {
            /**
             * Format: date
             * @description First day of the cycle, inclusive
             */
            starts_on: string;
            /**
             * Format: date
             * @description First day of the next cycle, exclusive
             */
            ends_on: string;
            balance: components["schemas"]["Balance"];
            /** @description One entry per category with a movement in the cycle: in before out, then by descending total, then by category id. */
            category_totals: components["schemas"]["CategoryTotal"][];
        };
        CategoryTotal: {
            /** Format: int64 */
            category_id: number;
            /** @enum {string} */
            direction: "in" | "out";
            /**
             * Format: int64
             * @description Sum of the category's movements in the cycle, in cents
             */
            total_cents: number;
            /** @description Movements of the category in the cycle */
            movement_count: number;
        };
        Balance: {
            /**
             * Format: int64
             * @description Sum of in movements, in cents
             */
            total_in: number;
            /**
             * Format: int64
             * @description Sum of out movements, in cents
             */
            total_out: number;
            /**
             * Format: int64
             * @description total_in minus total_out, in cents
             */
            net: number;
        };
        WidgetSettings: {
            /** @description Widget id to enabled. PUT must carry exactly these four ids; the server rejects any other mapping. The ids mirror the Go dashboard domain catalog — changing one means changing both. */
            widgets: {
                "net-balance": boolean;
                "total-income": boolean;
                "total-expenses": boolean;
                "category-distribution": boolean;
            };
        };
        Habit: {
            streak: {
                /** @description Consecutive logged days ending today, or yesterday when today is not yet logged. Counts across cycle boundaries. */
                current: number;
                today_logged: boolean;
            };
            /** @description Every day of the active cycle, first to last */
            days: {
                /** Format: date */
                date: string;
                /** @enum {string} */
                status: "logged" | "missed" | "today_logged" | "today_pending" | "ahead";
            }[];
            xp: {
                /** @description XP over every existing movement, all cycles */
                total: number;
                level: number;
                /** @description Total XP at which the current level started */
                level_starts_at: number;
                /** @description Total XP at which the next level starts */
                next_level_at: number;
            };
            /** @description XP earned by each movement dated in the active cycle */
            movement_xp: {
                /** Format: int64 */
                movement_id: number;
                xp: number;
            }[];
            /** @description The XP rules the server applies */
            rules: {
                id: string;
                label: string;
                xp: number;
            }[];
        };
        Error: {
            error: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listMovements: {
        parameters: {
            query?: {
                /** @description The page to return, from 1. A page beyond the last returns the last page. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of the active cycle's movements, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovementPage"];
                };
            };
            /** @description page is not a positive integer */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createMovement: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MovementInput"];
            };
        };
        responses: {
            /** @description Movement recorded */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Movement"];
                };
            };
            /** @description Invalid amount, direction, or date; unknown category; or category of the other direction */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateMovement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MovementInput"];
            };
        };
        responses: {
            /** @description Movement updated; its id and created_at are unchanged */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Movement"];
                };
            };
            /** @description Invalid id, amount, direction, or date; unknown category; or category of the other direction */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Movement not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteMovement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Movement deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Movement not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Seeded and user-created categories, in sort order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
            /** @description Unexpected server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryInput"];
            };
        };
        responses: {
            /** @description Category created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            /** @description Blank name or invalid direction */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A category with that name already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getCurrentCycle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The active cycle. ends_on is exclusive: the cycle covers [starts_on, ends_on). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentCycle"];
                };
            };
            /** @description Unexpected server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getWidgetSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The stored selection, or the all-enabled defaults when the user has never saved one. Unknown stored ids are dropped and missing ids fall back to their default. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WidgetSettings"];
                };
            };
            /** @description Unexpected server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    putWidgetSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WidgetSettings"];
            };
        };
        responses: {
            /** @description Selection stored; the response echoes it */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WidgetSettings"];
                };
            };
            /** @description The mapping has an unknown id, a missing id, or a value that is not a boolean; the stored selection is unchanged */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getHabit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The habit, or no habit at all on failure */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Habit"];
                };
            };
            /** @description Unexpected server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
